apiVersion: v1
kind: Service
metadata:
  name: my-app 
spec:
  type: NodePort  # Change from LoadBalancer to NodePort
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30000  
