name: CI/CD Pipeline for Minikube Deployment

on:
  push:
    branches:
      - main  # Runs when pushing to the main branch
  pull_request:
    branches:
      - main

env:
  IMAGE_NAME: ghcr.io/dipendu1/cicd/my-app:latest  # ✅ Ensure username is lowercase
  MINIKUBE_DRIVER: docker  # ✅ Minikube runs on Docker
  KUBERNETES_VERSION: v1.32.0  # ✅ Your Minikube/K8s version
  REGISTRY: ghcr.io  # ✅ GitHub Container Registry

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # ✅ Required for pushing to GitHub Container Registry (GHCR)

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t $IMAGE_NAME .
          echo "✅ Docker Image Built: $IMAGE_NAME"

      - name: Push Docker Image to GHCR
        run: |
          docker push $IMAGE_NAME
          echo "✅ Docker Image Pushed to GHCR"

  deploy:
    needs: build-and-push  # ✅ Only run after the image is built and pushed
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Minikube
        uses: medyagh/setup-minikube@latest
        with:
          driver: docker
          kubernetes-version: ${{ env.KUBERNETES_VERSION }}

      - name: Load Docker Image into Minikube
        run: |
          minikube image load $IMAGE_NAME
          echo "✅ Docker Image Loaded into Minikube"

      - name: Deploy to Minikube
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
          kubectl rollout status deployment/my-app
          echo "✅ Deployment Successful!"

      - name: Verify Deployment
        run: |
          kubectl get pods
          kubectl get services
